# Generated by Django 5.2.12 on 2026-04-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
        ('curso', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(to='alumno.alumno'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(to='profesor.profesor'),
        ),
    ]
