# Generated by Django 5.2.12 on 2026-04-13 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_titulo', models.CharField(max_length=100)),
                ('menu_ruta', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_icono', models.CharField(blank=True, default='ListBulletIcon', max_length=50)),
                ('menu_orden', models.IntegerField(default=0)),
                ('menu_activo', models.BooleanField(default=True)),
                ('menu_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('menu_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_hijos', to='menu.menu')),
            ],
        ),
    ]
